#!/usr/bin/env bash
#this is  a Bash script that stops 4-to_infinity_and_beyond process.
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

#Terminate the infinity processs

if [ -n "$id ]
then
  kill -15 "$id"
fi
